sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: jpt1452013
  alioss:
    #采用引用形式，到时候直接改环境就可以了
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: loveminmin
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx4b902e0ae0cd925d
    secret: bc27d21418f4b5852813e7ebf2040baf
    mchid: ${sky.wechat.mchid}
    mchSerialNo: ${sky.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiV3Key}
    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}